config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"audios#index"
  resources :users
  resources :audios do
    resources :comments,only: [:create]
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
  end
  resources :artists
  resources :groups do
    resources :chats,only: [:index,:create]
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :audios                           # 一人のアーティストは複数の楽曲(ユーザーが投稿した楽曲)を所有
  has_many :groups                           # 一人のアーティストは複数のユーザーチャットグループを所有
  has_many :users, through: :user_artists    # 一人のアーティストは複数のユーザーにフォローされる(中間テーブルのusers_artistsテーブルを経由)
  has_many :images                           # 一人のアーティストは複数の写真を所有
  


end

app/models/audio.rb
class Audio < ApplicationRecord
  mount_uploader :file, AudioFileUploader
  mount_uploader :image, ImageUploader

  belongs_to :user                     # 一つの楽曲は一人のユーザーに帰属 -->
  belongs_to :artist                   # 一つの楽曲は一人のアーティストに帰属 -->
  has_many :comments                   # 一つの楽曲は複数のユーザーのコメントを所有-->
  has_many :users,through: :likes      # 一つの楽曲はlikesテーブルを中間テーブルとし、複数のユーザーからいいねをもらう-->
  
  validates :title, presence: true
  # validates :file,  presence: true


end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user   # 一つのチャットは一人のユーザーが送信
  belongs_to :group   # 一つのチャットは一つのグループに所属
  


end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :user    # 一つのコメントは一人のユーザーに帰属
belongs_to :audio   # 一つのコメントは一人の楽曲に帰属
  


end

app/models/follow.rb
class Follow < ApplicationRecord

belongs_to :user       # ユーザーは複数のfollows情報を所有 -->
belongs_to :follower  # ユーザーはfollowsテーブルを中間テーブルとして、一人のフォローユーザーを所有 -->
  

end

app/models/follower.rb
class Follower < ApplicationRecord

  belongs_to :user                     # ユーザーは複数のfollowers情報を所有
  has_many :follows                    # フォロワーは複数のフォローユーザーを所有
  

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :users, through: :members      # グループは複数のユーザーが所属(中間テーブルのmembersテーブルを経由) -->
  has_many :chats                         # グループでは複数のチャットが交わされる -->
  belongs_to :artist                      # グループには一人のアーティストが存在 -->
  

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :artist
  belongs_to :user



end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user       # 一つのいいねは一人のユーザーに帰属 -->
  belongs_to :audios     # 一つのいいねは一つの楽曲に帰属 -->
  

end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :user
  belongs_to :group



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :userimage,ImageUploader
  mount_uploader :backgroundimage,ImageUploader
   

  has_many :audios                              # ユーザーは複数の楽曲データを所有 -->
  has_many :groups, through: :members           # ユーザーは複数のグループに所属(中間テーブルのmembersテーブルを経由) -->
  has_many :chats                               # ユーザーは複数のチャットを送信できる -->
  has_many :artists, through: :users_artists    # ユーザーは複数のアーティストをフォローできる(中間テーブルのusers_artistsテーブルを経由) -->
  has_many :follows                             # ユーザーは複数のユーザーをフォローできる -->
  has_many :follwers                            # ユーザーは複数のユーザーにフォローされる -->
  has_many :comments                            # ユーザーは投稿に対し、複数のコメントを残すことができる -->
  has_many :audios, through: :likes             # ユーザーはlikesテーブルを中間テーブルとし、複数の楽曲にいいねをつけることができる -->
  has_many :images                              # ユーザーはアーティストの画像を複数枚投稿できる -->
         

end

app/models/user_artist.rb
class UserArtist < ApplicationRecord

  belongs_to :user
  belongs_to :artist



end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  before_action :set_audio,except: [:index,:new,:create]
  
  def index    #トップページ
    @audios = Audio.order("created_at DESC")
  end

  def show     #楽曲詳細ページ
    #ユーザーのその他の投稿項目が最新の8項目のみ表示されるようにする
    @useraudio = Audio.where(user_id:@audio.user_id).order("created_at DESC").limit(8)
    @comment = Comment.new
    @comments = Comment.where(audio_id:@audio.id).order("created_at ASC")
  end
  
  #mp3ファイル取り出しの例
    # audio = Audio.find(1)
    # audio.file.mp3.url →/uploads/audio/file/1/sample1.mp3
  def new
    @audio = Audio.new
  end
    
  def create
    # DB登録時、artistnameまたはartist_idが入っていれば登録できるようにする！
    @audio=Audio.new(audio_params)
    if @audio.save
      redirect_to root_path
    else
      redirect_to new_audio_path
    end
  end

  def update
    if @audio.update(audio_params)
      redirect_to "/audios/#{@audio.id}"
    end
  end

  def destroy
    if @audio.destroy
      redirect_to root_path
    end
  end

  def edit
  end

  private

  def audio_params
    params.require(:audio).permit(:title,:category,:image,:file,:description,:artistname).merge(user_id: current_user.id,artist_id:1)
  end

  def set_audio
    @audio = Audio.find(params[:id])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

def index  #チャットルーム
end

def create
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @audios = Audio.where(user_id:current_user.id).order("created_at DESC")
  end
  
  def show
    @user = User.find(params[:id])
    @audios = Audio.where(user_id:@user.id).order("created_at DESC")
  end

  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to "/users/#{@user.id}"
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname,:email,:introduction,:userimage,:backgroundimage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/audios/_header-sidebar.html.haml
= render partial: "audios/header"
.main
  = render partial: "audios/sidebar2"
  = render partial: "audios/sidebar1"

app/views/audios/_header.html.haml
.header
  .index_header
    .index_header__sidebaricon
      %i.fas.fa-bars{width:"20px",height:"20px",onclick:"CloseSidebar()"}
      = link_to image_tag("logo.jpg",class:"logo"),root_path
    .index_header__searchbar
      =form_with do |f|
        .index_header__searchbar__change
          %i.fas.fa-search{onclick:"ChaneForm()"}
        #formmusic.index_header__searchbar__form
          =f.text_field :title,class:"audiotitle1",id:"audiotitle11",placeholder:"曲名を入力してください",cols:"30",rows:"1"
        #formartist.display_none
          =f.text_field :title,class:"audiotitle1",id:"audiotitle12",placeholder:"アーティストを入力してください",cols:"30",rows:"1"     
        #formchatgroup.display_none
          =f.text_field :title,class:"audiotitle1",id:"audiotitle13",placeholder:"チャットグループを入力してください",cols:"30",rows:"1"
    .index_header__post
      = link_to new_audio_path do
        %i.fas.fa-cloud-upload-alt.fa-2x
      .index_header__userimage
        -if user_signed_in?
          -if current_user.userimage.present?
            = link_to image_tag("#{current_user.userimage}",class:"userphoto"),"/users/#{current_user.id}"
          -else
            = link_to image_tag("member_photo_noimage.png",class:"userphoto"),"/users/#{current_user.id}"
        -else 
          = link_to image_tag("member_photo_noimage.png",class:"userphoto"),new_user_session_path

app/views/audios/_main.html.haml
.yohaku
#mainadd.main1
  .annnai
    投稿の詳細を表示するにはクリックしてください
  - @audios.each do |audio|
    .music-form
      -# link_toの中は、楽曲の画像もしくは再生ボタン 
      -if audio.image.url.present? 
        = link_to image_tag(audio.image.url,class:"musicview1"),audio_path(audio.id)
      - else
        = link_to image_tag("logo.jpg",class:"musicview1"),audio_path(audio.id)
      %li 
        = audio.title
      %li 
        = audio.artistname
      %li 
        = link_to audio.user.nickname,"/users/#{audio.user.id}"
      %li 100いいね

app/views/audios/_post.html.haml
= render partial: "header-sidebar"
.yohaku
#mainadd.main1
  .audiosnew
    .audiosnew__top
      %p 楽曲投稿
    .audiosnew__form
      = form_with(model:audio,local: true,multipart: true) do |f|
        .audiosnew__form__titlelabel
          =f.label :title,"タイトル",class:"audiotitlelabel"
          =f.label :title,"必須",class:"audiohissulabel"
        .audiosnew__form__titleform
          =f.text_field :title,placeholder:"タイトルを入力してください",class:"audiotitleform"
        .audiosnew__form__artistlabel
          =f.label :artistname,"アーティスト"
          =f.label :artistname,"必須",class:"audiohissulabel"
        .audiosnew__form__artistform
          =f.text_field :artistname,placeholder:"アーティストを入力してください",class:"audioartistform"
        .audiosnew__form__categorylabel
          =f.label :category,"カテゴリー",class:"audiocategorylabel"
        .audiosnew__form__categoryform
          =f.text_field :category,placeholder:"カテゴリーを入力してください",class:"audiocategoryform"
        .audiosnew__form__descriptionlabel
          =f.label :description,"あなたの一押しポイント",class:"audiodescriptionlabel"
        .audiosnew__form__descriptionform
          =f.text_area :description,class:"audiodiscriptionform"
        .audiosnew__form__imagelabel
          =f.label :image,"楽曲の画像"
          =f.label :image,class:"audioimagemusicform",id:"imageupload" do
            .audiosnew__form__imageform
              %i.far.fa-image.fa-2x
              =f.file_field :image,class:"display_none"
          -# .audiosnew__form__imageform__preview
          -#   = image_tag "",id:"imagepreview"
        .audiosnew__form__filelabel
          =f.label :file,"音源"
          =f.label :file,"必須",class:"audiohissulabel"
          =f.label :file,"⚠️mp3ファイルのみ投稿できます！"
          =f.label :file,class:"audiofileform" do
            .audiosnew__form__fileform
              %i.fas.fa-music.fa-2x   
              =f.file_field :file,class:"display_none"
        .audiosnew__form__send
          = f.submit "投稿",class:"submit"

app/views/audios/_sidebar1.html.haml
#sidebaradd.index_sidebar1
  .index_sidebar1__home
    =link_to root_path do
      %li ホーム
  .index_sidebar1__home
    =link_to "" do
      %li グループ
  .index_sidebar1__home
    =link_to users_path do
      %li あなたの投稿
  .index_sidebar1__home
    =link_to "" do
      %li
  -if user_signed_in?
    .index_sidebar1__home
      = link_to destroy_user_session_path,method: :delete do
        %li ログアウト
  -else
    .index_sidebar1__home
      = link_to new_user_session_path do
        %li ログイン

app/views/audios/_sidebar2.html.haml
#sidebarnone.index_sidebar2
  .index_sidebar2__home
    =link_to root_path do
      %i.fas.fa-home.fa-2x
  .index_sidebar2__home
    =link_to "" do
      %i.fas.fa-user-friends.fa-2x
  .index_sidebar2__home
    =link_to users_path do
      %i.fas.fa-music.fa-2x
  .index_sidebar2__home
    =link_to "" do
      %i.fab.fa-napster.fa-2x
  -if user_signed_in?
    .index_sidebar2__home
      = link_to destroy_user_session_path,method: :delete  do
        %i.fas.fa-sign-out-alt.fa-2x
  -else
    .index_sidebar2__home
      = link_to new_user_session_path do
        %i.fab.fa-linkedin-in.fa-2x

app/views/audios/edit.html.haml
=render partial: "post",locals: {audio: @audio}

app/views/audios/index.html.haml
= render partial: "header-sidebar"
= render partial: "main" 

app/views/audios/new.html.haml
= render partial: "header-sidebar"
.yohaku
#mainadd.main1
  .audiosnew
    .audiosnew__top
      %p 楽曲投稿
    .audiosnew__form
      = form_with(model:@audio,local: true,multipart: true) do |f|
        .audiosnew__form__titlelabel
          =f.label :title,"タイトル",class:"audiotitlelabel"
          =f.label :title,"必須",class:"audiohissulabel"
        .audiosnew__form__titleform
          =f.text_field :title,placeholder:"タイトルを入力してください",class:"audiotitleform"
        .audiosnew__form__artistlabel
          =f.label :artistname,"アーティスト"
          =f.label :artistname,"必須",class:"audiohissulabel"
        .audiosnew__form__artistform
          =f.text_field :artistname,placeholder:"アーティストを入力してください",class:"audioartistform"
        .audiosnew__form__categorylabel
          =f.label :category,"カテゴリー",class:"audiocategorylabel"
        .audiosnew__form__categoryform
          =f.text_field :category,placeholder:"カテゴリーを入力してください",class:"audiocategoryform"
        .audiosnew__form__descriptionlabel
          =f.label :description,"あなたの一押しポイント",class:"audiodescriptionlabel"
        .audiosnew__form__descriptionform
          =f.text_area :description,class:"audiodiscriptionform"
        .audiosnew__form__imagelabel
          =f.label :image,"楽曲の画像"
          =f.label :image,class:"audioimagemusicform" do
            .audiosnew__form__imageform
              %i.far.fa-image.fa-2x
              =f.file_field :image,class:"display_none"
        .audiosnew__form__filelabel
          =f.label :file,"音源"
          =f.label :file,"必須",class:"audiohissulabel"
          =f.label :file,"⚠️mp3ファイルのみ投稿できます！"
          =f.label :file,class:"audiofileform" do
            .audiosnew__form__fileform
              %i.fas.fa-music.fa-2x   
              =f.file_field :file,class:"display_none"
        .audiosnew__form__send
          = f.submit "投稿",class:"submit"

app/views/audios/show.html.haml
= render partial: "header-sidebar"
.yohaku
#mainadd.main1
  .fafafa
    .show
      .show__top
        .display_none.hidoukiid
          =@audio.id
        -if @audio.image.url.present?
          =image_tag(@audio.image.url,class:"musicview")
        -else
          =image_tag("logo.jpg",class:"musicview")
      .show__discription   
        .show__discription__about
          %li タイトル
          %p 
            = @audio.title
        .show__discription__about
          %li アーティスト
          %p 
            = @audio.artistname
        .show__discription__about
          %li カテゴリー
          - if @audio.category.present?
            %p 
              = @audio.category
          - else
            %p 
              なし
        -if user_signed_in?
          - if current_user.id == @audio.user.id 
            .show__discription__about
              .show__discription__about__edit
                = link_to "編集する", "/audios/#{@audio.id}/edit"
                = link_to "削除する", "/audios/#{@audio.id}/",method: :delete,onClick:"alert('削除しました');"
        .jkjk
          = audio_tag(@audio.file.mp3.url,class:"musicstart")
  .show__discription__under
    .user__image
      - if @audio.user.userimage.present?
        = link_to image_tag("#{@audio.user.userimage}",class:"userphoto"),"/users/#{@audio.user.id}"
      - else
        = link_to image_tag("member_photo_noimage.png",class:"userphoto"),"/users/#{@audio.user.id}"
      = @audio.user.nickname
      さんの一押しポイント
    - if @audio.description.present?
      %p 
        = @audio.description
    - else
      %p
        なし
    .users-list{onclick:"UserPost()"}
      =@audio.user.nickname
      さんの最近の投稿
      %i#toukouyajirushi.fas.fa-chevron-down
    #userpost.display_none
      - @useraudio.each do |useraudio|
        .music-form
          -if useraudio.image.url.present?
            = link_to image_tag(useraudio.image.url,class:"musicview1"),"/audios/#{useraudio.id}"
          -else
            = link_to image_tag("logo.jpg",class:"musicview1"),""
          %li 
            = useraudio.title
          %li 
            = useraudio.artistname
    #usercomment.comment2
      .comment__list{onclick:"CommentPost()"}
        コメント一覧
        %i#commentyajirushi.fas.fa-chevron-down
    #commentpost.display_none
      .talktalk
        - @comments.each do |comment|
          .talk{"data-comment-id": "#{comment.id}"}
            .user__image
              -if comment.user.userimage.present?
                = link_to image_tag("#{comment.user.userimage}",class:"userphoto"),"/users/#{comment.user_id}"
              -else
                = link_to image_tag("member_photo_noimage.png",class:"userphoto"),"/users/#{comment.user_id}"
            .user-chat
              %p 
                = comment.comment
      .yohaku2
      .chatsindex
        =form_with(model:@comment,local: true,url:"/audios/#{@audio.id}/comments",method: :post,id:"newcomment")do |f|
          #textform.chatsindex__textform1
            = f.text_field :comment,class:"chatsform",placeholder:"コメントを入力してください",cols:"30",rows:"1"
            = f.submit "送信",class:"submit"
    %script
      audiojs.events.ready(function() {
      var as = audiojs.createAll();
      });